# Generated by Django 6.0.4 on 2026-06-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('MERCHANT', 'Merchant')], max_length=10),
        ),
    ]
