# Generated by Django 6.0.4 on 2026-06-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='solicitacao',
            field=models.CharField(choices=[('Suporte', 'Suporte'), ('Atendimento', 'Atendimento')], default='Atendimento', max_length=20),
            preserve_default=False,
        ),
    ]
