# Generated by Django 6.0.4 on 2026-06-11 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('street', 'number', 'city', 'state', 'cep'), name='unique_address'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
