# Generated by Django 6.0.4 on 2026-06-09 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_contato_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('crédito', 'Crédito'), ('débito', 'Débito'), ('boleto', 'Boleto')], max_length=15, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
