# Generated by Django 6.0.4 on 2026-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_address_user_address_unique_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='users', to='Users.address'),
        ),
    ]
