# Generated by Django 6.0.4 on 2026-06-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_address_user_users_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethoduser',
            name='customer',
        ),
        migrations.AlterField(
            model_name='users',
            name='addresses',
            field=models.ManyToManyField(blank=True, default=0, related_name='users', to='Users.address'),
        ),
        migrations.AddField(
            model_name='paymentmethoduser',
            name='customer',
            field=models.ManyToManyField(related_name='payments_methods', to=settings.AUTH_USER_MODEL),
        ),
    ]
