# Generated by Django 6.0.4 on 2026-06-15 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_paymentmethoduser_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethoduser',
            name='customer',
        ),
        migrations.AddField(
            model_name='paymentmethoduser',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_methods', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
