# Generated by Django 6.0.4 on 2026-06-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_paymentmethoduser_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethoduser',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BOLETO', 'Boleto')], default='pix', max_length=15),
            preserve_default=False,
        ),
    ]
