# Generated by Django 6.0.4 on 2026-05-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
