# Generated by Django 6.0.4 on 2026-06-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
