# Generated by Django 6.0.4 on 2026-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_itempedido_preco_unitario_alter_carrinho_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('calcas', 'Calças'), ('camisas', 'Camisas'), ('bermudas', 'Bermudas'), ('vestidos', 'Vestidos'), ('saias', 'Saias'), ('shorts', 'Shorts'), ('blusas', 'Blusas')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
