# Generated by Django 6.0.4 on 2026-05-29 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_produto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='cor',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sku',
            name='tamanho',
            field=models.CharField(default='qualquer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('nome', 'preco', 'descricao'), name='unique_produto_nome_preco_descricao'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('produto', 'cor', 'tamanho'), name='unique_produto_cor_tamanho'),
        ),
    ]
