# Generated by Django 6.0.4 on 2026-06-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_carrinho_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='total',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='subtotal',
        ),
    ]
