# Generated by Django 6.0.4 on 2026-05-29 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_produto_unique_produto_nome_preco_descricao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produto',
            name='unique_produto_nome_preco_descricao',
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('users', 'nome', 'preco', 'descricao'), name='unique_produto_por_lojista'),
        ),
    ]
