# Generated by Django 6.0.4 on 2026-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_carrinho_total_remove_itemcarrinho_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('crédito', 'Crédito'), ('débito', 'Débito'), ('boleto', 'Boleto')], default='pix'),
            preserve_default=False,
        ),
    ]
