# Generated by Django 6.0.4 on 2026-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='produto_nome_save',
            field=models.CharField(default='teste', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cor_save',
            field=models.CharField(default='branco', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='tamanho_save',
            field=models.CharField(default='p', max_length=50),
            preserve_default=False,
        ),
    ]
