# Generated by Django 6.0.4 on 2026-05-29 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_produto_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produto',
            name='unique_produto_por_lojista',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='users',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('user', 'nome', 'preco', 'descricao'), name='unique_produto_por_lojista'),
        ),
    ]
