# Generated by Django 6.0.4 on 2026-06-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_itemcarrinho_carrinho_alter_itempedido_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='user',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='lojista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
